# **********************************************
# 제 목 : 10-4
# 날 짜 : 2025년 11월27일
# 작성자 : 2001485 김선우
# **********************************************
CXX = g++
CXXFLAGS = -std=c++17 -Wall -O2

TARGET = run
SRC = main.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
