# **********************************************
# 제 목 :  10-3
# 날 짜 :  2025년11월26일
# 작성자 :  2001485 김선우
# **********************************************
CXX = g++
CXXFLAGS = -std=c++17 -Wall

TARGET = main
SRC = main.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
