# **********************************************
# 제 목 : 10-1
# 날 짜 : 2025년 11월20일
# 작성자 : 2001485 김선우 
# **********************************************
CXX = g++
CXXFLAGS = -Wall -std=c++17

TARGET = main
SRCS = main.cpp

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRCS)

clean:
	rm -f $(TARGET)
